[versions]
precompose = "1.6.2"
dokka = "2.1.0"
theme = "2.2.0"
compose = "1.9.3"
kotlin = "2.3.0"
kotlinter = "5.3.0"
agp = "8.13.2"
android-minSdk = "24"
android-compileSdk = "36"
vanniktech = "0.35.0"

[libraries]
precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }
malefic-theming = { module = "xyz.malefic.compose:theming", version.ref = "theme" }

[plugins]
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
