[versions]
precompose = "1.6.2"
dokka = "2.0.0"
theme = "2.0.5"
compose = "1.9.3"
kotlin = "2.2.10"
kotlinter = "5.2.0"
agp = "8.11.1"
android-minSdk = "24"
android-compileSdk = "36"
vanniktech = "0.34.0"

[libraries]
precompose = { group = "moe.tlaster", name = "precompose", version.ref = "precompose" }
malefic-theming = { module = "xyz.malefic.compose:theming", version.ref = "theme" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech" }
